# Mailozaurr.Libraries.ps1
# Auto-generated by PowerForge. Do not edit.

$LibrariesByFolder = @{
    'Core' = @(
        'Lib\Core\Mailozaurr.PowerShell.dll'
        'Lib\Core\BouncyCastle.Cryptography.dll'
        'Lib\Core\EmailValidation.dll'
        'Lib\Core\Google.Apis.Auth.dll'
        'Lib\Core\Google.Apis.Core.dll'
        'Lib\Core\Google.Apis.dll'
        'Lib\Core\MailKit.dll'
        'Lib\Core\Mailozaurr.dll'
        'Lib\Core\Microsoft.Identity.Client.dll'
        'Lib\Core\Microsoft.IdentityModel.Abstractions.dll'
        'Lib\Core\MimeKit.dll'
        'Lib\Core\Newtonsoft.Json.dll'
        'Lib\Core\NSspi.dll'
        'Lib\Core\OfficeIMO.Drawing.dll'
        'Lib\Core\OfficeIMO.Email.dll'
        'Lib\Core\OfficeIMO.Rtf.dll'
        'Lib\Core\System.CodeDom.dll'
    )
    'Default' = @(
        'Lib\Default\Mailozaurr.PowerShell.dll'
        'Lib\Default\BouncyCastle.Cryptography.dll'
        'Lib\Default\EmailValidation.dll'
        'Lib\Default\Google.Apis.Auth.dll'
        'Lib\Default\Google.Apis.Core.dll'
        'Lib\Default\Google.Apis.dll'
        'Lib\Default\MailKit.dll'
        'Lib\Default\Mailozaurr.dll'
        'Lib\Default\Microsoft.Bcl.AsyncInterfaces.dll'
        'Lib\Default\Microsoft.Identity.Client.dll'
        'Lib\Default\Microsoft.IdentityModel.Abstractions.dll'
        'Lib\Default\MimeKit.dll'
        'Lib\Default\Newtonsoft.Json.dll'
        'Lib\Default\NSspi.dll'
        'Lib\Default\OfficeIMO.Drawing.dll'
        'Lib\Default\OfficeIMO.Email.dll'
        'Lib\Default\OfficeIMO.Rtf.dll'
        'Lib\Default\System.Buffers.dll'
        'Lib\Default\System.Diagnostics.DiagnosticSource.dll'
        'Lib\Default\System.Formats.Asn1.dll'
        'Lib\Default\System.IO.Pipelines.dll'
        'Lib\Default\System.Memory.dll'
        'Lib\Default\System.Numerics.Vectors.dll'
        'Lib\Default\System.Runtime.CompilerServices.Unsafe.dll'
        'Lib\Default\System.Text.Encoding.CodePages.dll'
        'Lib\Default\System.Text.Encodings.Web.dll'
        'Lib\Default\System.Text.Json.dll'
        'Lib\Default\System.Threading.Tasks.Extensions.dll'
    )
}


$AssemblyFolders = Get-ChildItem -Path $PSScriptRoot\Lib -Directory -ErrorAction SilentlyContinue

$Default = $false
$Core = $false
$Standard = $false
foreach ($A in $AssemblyFolders.Name) {
    if ($A -eq 'Default') {
        $Default = $true
    } elseif ($A -eq 'Core') {
        $Core = $true
    } elseif ($A -eq 'Standard') {
        $Standard = $true
    }
}
if ($Standard -and $Core -and $Default) {
    $FrameworkNet = 'Default'
    $Framework = 'Standard'
} elseif ($Standard -and $Core) {
    $Framework = 'Standard'
    $FrameworkNet = 'Standard'
} elseif ($Core -and $Default) {
    $Framework = 'Core'
    $FrameworkNet = 'Default'
} elseif ($Standard -and $Default) {
    $Framework = 'Standard'
    $FrameworkNet = 'Default'
} elseif ($Standard) {
    $Framework = 'Standard'
    $FrameworkNet = 'Standard'
} elseif ($Core) {
    $Framework = 'Core'
    $FrameworkNet = ''
} elseif ($Default) {
    $Framework = ''
    $FrameworkNet = 'Default'
} else {
    #Write-Error -Message 'No assemblies found'
}

if ($PSEdition -eq 'Core') {
    $LibFolder = $Framework
} else {
    $LibFolder = $FrameworkNet
}

$LibrariesToLoad = $LibrariesByFolder[$LibFolder]
if ($null -eq $LibrariesToLoad) { $LibrariesToLoad = @() }
foreach ($L in $LibrariesToLoad) {
    try {
        $LibraryPathParts = @($PSScriptRoot) + @($L -split '[\\/]' | Where-Object { -not [string]::IsNullOrWhiteSpace($_) })
        $LibraryPath = [IO.Path]::Combine([string[]] $LibraryPathParts)
        try {
            $null = [System.Reflection.AssemblyName]::GetAssemblyName($LibraryPath)
        } catch [System.BadImageFormatException] {
            Write-Verbose -Message "Skipping non-managed library '$L'."
            continue
        }

        Add-Type -Path $LibraryPath -ErrorAction Stop
    } catch {
        if ($_.Exception.Message -like '*Assembly with same name is already loaded*') {
            Write-Warning -Message "Assembly with same name is already loaded. Ignoring '$L'."
        } else {
            throw $_
        }
    }
}
