jobs:
  - job: Windows_PowerShell_5
    pool:
      vmImage: windows-latest
    steps:
      - powershell: |
          Install-Module -Name Pester -Repository PSGallery -Force -SkipPublisherCheck
          .\Mailozaurr.Tests.ps1 -Verbose
        displayName: "Run Tests on Windows PowerShell 5.1"

  - job: Windows_PowerShell_7
    pool:
      vmImage: windows-latest
    steps:
      - pwsh: 'Install-Module -Name Pester -Repository PSGallery -Force -SkipPublisherCheck'
        displayName: "Update PESTER"
      - pwsh: '.\Mailozaurr.Tests.ps1 -Verbose'
        displayName: "Run Tests on Windows PowerShell 7"


  - job: Linux_Ubuntu

    pool:
      vmImage: ubuntu-latest

    steps:
      - script: |
          curl -sSL https://packages.microsoft.com/config/ubuntu/20.04/prod.list | sudo tee /etc/apt/sources.list.d/microsoft-prod.list
          curl -sSL https://packages.microsoft.com/keys/microsoft.asc | sudo tee /etc/apt/trusted.gpg.d/microsoft.asc
          sudo apt-get update
          sudo apt-get install -y powershell
        displayName: "Install PowerShell Core"

      - powershell: '.\Mailozaurr.Tests.ps1'
        displayName: "Run Tests on Linux"

  - job: MacOS
    pool:
      vmImage: macOS-latest
    steps:
      - script: |
          brew update
          brew tap caskroom/cask
          brew install mono-libgdiplus
          brew install --cask powershell
        displayName: "Install PowerShell 7"

      - powershell: '.\Mailozaurr.Tests.ps1'
        displayName: "Run Tests on MacOs"
