using System.CommandLine;

namespace Mailozaurr.Cli;

internal static partial class CliCommandModel {
    private static Command CreateMailCommand() => Group(
        "mail",
        "Read mailboxes, preview actions, execute confirmed actions, and manage action-plan batches.",
        Leaf("folders", "List mailbox folders.",
            required: ["profile"], optional: ["mailbox", "parent-folder", "root-only", "compact"]),
        Leaf("folder-aliases", "List normalized folder aliases.",
            required: ["profile"], optional: ["mailbox"]),
        Leaf("resolve-folder", "Resolve a folder identifier or alias.",
            required: ["profile", "target-folder"], optional: ["mailbox"]),
        Leaf("list-plan-batches", "List stored action-plan batches.",
            optional: ["summary", "compact", "plan-name", "profile", "action", "sort", "desc"]),
        Leaf("show-plan-batch", "Show a stored action-plan batch.",
            required: ["batch"], optional: ["summary", "compact"]),
        Leaf("import-plan-batch", "Import an action-plan batch from a file.",
            required: ["batch", "name", "path"], optional: ["description"]),
        Leaf("export-plan-batch", "Export a stored action-plan batch.",
            required: ["batch", "path"]),
        Leaf("create-common-plan-batch", "Create a batch from common actions and message ids.",
            required: ["batch", "name", "profile", "message-id"],
            optional: ["action", "target-folder", "mailbox", "folder", "description"]),
        Leaf("clone-plan-batch", "Clone a stored action-plan batch.",
            required: ["source-batch", "target-batch", "name"], optional: ["description"]),
        Leaf("preview-transform-plan-batch", "Preview a selective batch transform.",
            required: ["source-batch"],
            optional: ["index", "plan-name", "target-profile", "mailbox", "folder", "target-folder"]),
        Leaf("transform-plan-batch", "Transform and clone a stored action-plan batch.",
            required: ["source-batch", "target-batch", "name"],
            optional: [
                "index", "plan-name", "target-profile", "mailbox", "folder", "target-folder",
                "description"
            ]),
        Leaf("add-plan-to-batch", "Append a normalized action plan to a stored batch.",
            required: ["batch", "action", "profile", "message-id"],
            optional: ["target-folder", "mailbox", "folder", "confirm-token"]),
        Leaf("add-plan-file-to-batch", "Append an imported action plan to a stored batch.",
            required: ["batch", "path"]),
        Leaf("replace-plan-in-batch", "Replace one stored plan with a normalized plan.",
            required: ["batch", "index", "action", "profile", "message-id"],
            optional: ["target-folder", "mailbox", "folder", "confirm-token"]),
        Leaf("replace-plan-file-in-batch", "Replace one stored plan from an imported file.",
            required: ["batch", "index", "path"]),
        Leaf("remove-plan-from-batch", "Remove one plan from a stored batch.",
            required: ["batch", "index"]),
        Leaf("delete-plan-batch", "Delete a stored action-plan batch.", required: ["batch"]),
        Leaf("execute-plan-batch-stored", "Execute a stored action-plan batch.",
            required: ["batch"], optional: ["confirm-token", "stop-on-error"]),
        Leaf("preview-move", "Preview a move and return its confirmation token.",
            required: ["profile", "message-id", "target-folder"], optional: ["mailbox", "folder"]),
        Leaf("preview-actions", "Preview common message actions.",
            required: ["profile", "message-id"], optional: ["target-folder", "mailbox", "folder"]),
        Leaf("preview-all", "Preview all supported common message actions.",
            required: ["profile", "message-id"], optional: ["target-folder", "mailbox", "folder"]),
        Leaf("plan-action", "Create a normalized action execution plan.",
            required: ["action", "profile", "message-id"],
            optional: ["target-folder", "mailbox", "folder", "confirm-token"]),
        Leaf("export-plan", "Export a normalized action execution plan.",
            required: ["action", "profile", "message-id", "path"],
            optional: ["target-folder", "mailbox", "folder", "confirm-token"]),
        Leaf("show-plan", "Show an exported action plan.", required: ["path"]),
        Leaf("execute-plan", "Execute a normalized action plan.",
            required: ["action", "profile", "message-id"],
            optional: ["target-folder", "mailbox", "folder", "confirm-token"]),
        Leaf("execute-plan-file", "Execute an exported action plan.", required: ["path"]),
        Leaf("execute-plan-batch", "Execute an exported action-plan batch.",
            required: ["path"], optional: ["stop-on-error"]),
        Leaf("preview-delete", "Preview deletion and return its confirmation token.",
            required: ["profile", "message-id"], optional: ["mailbox", "folder"]),
        Leaf("preview-mark-read", "Preview a read-state change and return its confirmation token.",
            required: ["profile", "message-id"], optional: ["mailbox", "folder", "unread"]),
        Leaf("preview-flag", "Preview a flagged-state change and return its confirmation token.",
            required: ["profile", "message-id"], optional: ["mailbox", "folder", "unflag"]),
        Leaf("search", "Search messages.",
            required: ["profile"],
            optional: [
                "mailbox", "folder", "query", "subject", "from", "to", "has-attachments", "limit",
                "compact"
            ]),
        Leaf("get", "Get one message.",
            required: ["profile", "message-id"],
            optional: ["mailbox", "folder", "include-raw", "compact"]),
        Leaf("get-many", "Get multiple messages.",
            required: ["profile", "message-id"],
            optional: ["mailbox", "folder", "include-raw", "compact"]),
        Leaf("mark-read", "Execute a confirmed read-state change.",
            required: ["profile", "message-id"],
            optional: ["mailbox", "folder", "unread", "confirm-token"]),
        Leaf("flag", "Execute a confirmed flagged-state change.",
            required: ["profile", "message-id"],
            optional: ["mailbox", "folder", "unflag", "confirm-token"]),
        Leaf("move", "Execute a confirmed message move.",
            required: ["profile", "message-id", "target-folder"],
            optional: ["mailbox", "folder", "confirm-token"]),
        Leaf("archive", "Execute a confirmed archive action.",
            required: ["profile", "message-id"], optional: ["mailbox", "folder", "confirm-token"]),
        Leaf("trash", "Execute a confirmed trash action.",
            required: ["profile", "message-id"], optional: ["mailbox", "folder", "confirm-token"]),
        Leaf("delete", "Execute a confirmed delete action.",
            required: ["profile", "message-id"], optional: ["mailbox", "folder", "confirm-token"]),
        Leaf("attachments", "List message attachments.",
            required: ["profile", "message-id"], optional: ["mailbox", "folder"]),
        Leaf("save-attachment", "Save one attachment.",
            required: ["profile", "message-id", "attachment-id", "path"],
            optional: ["mailbox", "folder", "overwrite"]),
        Leaf("save-attachments", "Save selected attachments from one message.",
            required: ["profile", "message-id", "path"],
            optional: [
                "mailbox", "folder", "attachment-id", "name-contains", "content-type", "overwrite"
            ]),
        Leaf("save-attachments-many", "Save selected attachments from multiple messages.",
            required: ["profile", "message-id", "path"],
            optional: [
                "mailbox", "folder", "attachment-id", "name-contains", "content-type", "overwrite"
            ]));
}
