<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net472;net8.0</TargetFrameworks>
        <OutputType>Exe</OutputType>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <LangVersion>latest</LangVersion>
        <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
        <GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <NoWarn>$(NoWarn);xUnit1051</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="coverlet.collector" Version="10.0.1" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.7.0" />
        <PackageReference Include="Moq" Version="4.20.72" />
        <PackageReference Include="PowerShellStandard.Library" Version="5.1.1" PrivateAssets="all" />
        <PackageReference Include="xunit.v3" Version="3.2.2" />
        <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit" />
    </ItemGroup>

    <ItemGroup Condition=" '$(TargetFramework)' == 'net472' ">
        <Reference Include="System.IO.Compression" />
    </ItemGroup>

  <ItemGroup>
        <ProjectReference Include="..\Mailozaurr.Cli\Mailozaurr.Cli.csproj" Condition=" '$(TargetFramework)' == 'net8.0' " />
        <ProjectReference Include="..\Mailozaurr.Application\Mailozaurr.Application.csproj" />
        <ProjectReference Include="..\Mailozaurr\Mailozaurr.csproj" />
        <ProjectReference Include="..\Mailozaurr.Msg\Mailozaurr.Msg.csproj" />
        <ProjectReference Include="..\Mailozaurr.PowerShell\Mailozaurr.PowerShell.csproj" />
        <ProjectReference Include="..\Mailozaurr.Examples\Mailozaurr.Examples.csproj" Condition=" '$(TargetFramework)' == 'net8.0' " />
  </ItemGroup>

</Project>
