using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Mailozaurr;

/// <summary>Source-generated metadata used by Mailozaurr for AOT-safe JSON serialization.</summary>
[JsonSourceGenerationOptions(PropertyNameCaseInsensitive = true, DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull)]
[JsonSerializable(typeof(SmtpResult))]
[JsonSerializable(typeof(PendingMessageRecord))]
[JsonSerializable(typeof(PendingMessageLogEnvelope))]
[JsonSerializable(typeof(SentMessageRecord))]
[JsonSerializable(typeof(OAuthCredential))]
[JsonSerializable(typeof(Dictionary<string, OAuthCredential>))]
[JsonSerializable(typeof(Dictionary<string, string>))]
[JsonSerializable(typeof(Dictionary<string, bool>), TypeInfoPropertyName = "DictionaryStringBool")]
[JsonSerializable(typeof(Dictionary<string, int>), TypeInfoPropertyName = "DictionaryStringInt")]
[JsonSerializable(typeof(Dictionary<string, double>), TypeInfoPropertyName = "DictionaryStringDouble")]
[JsonSerializable(typeof(Dictionary<string, long>), TypeInfoPropertyName = "DictionaryStringLong")]
[JsonSerializable(typeof(Dictionary<string, object>))]
[JsonSerializable(typeof(Dictionary<string, JsonElement>))]
[JsonSerializable(typeof(Dictionary<string, object?>), TypeInfoPropertyName = "DictionaryStringObjectNullable")]
[JsonSerializable(typeof(Dictionary<string, JsonElement?>))]
[JsonSerializable(typeof(object), TypeInfoPropertyName = "Object")]
[JsonSerializable(typeof(JsonElement))]
[JsonSerializable(typeof(GraphAuthorization))]
[JsonSerializable(typeof(GraphApiError))]
[JsonSerializable(typeof(GraphApiErrorDetail))]
[JsonSerializable(typeof(GraphApiInnerError))]
[JsonSerializable(typeof(GraphApiDiagnostic))]
[JsonSerializable(typeof(GraphApiErrorHeaders))]
[JsonSerializable(typeof(GraphApiErrorResponse))]
[JsonSerializable(typeof(GraphApiServerInfo))]
[JsonSerializable(typeof(GraphUploadSessionResult))]
[JsonSerializable(typeof(GraphMessage))]
[JsonSerializable(typeof(GraphMessageContainer))]
[JsonSerializable(typeof(GraphContent))]
[JsonSerializable(typeof(GraphEmailAddress))]
[JsonSerializable(typeof(GraphEmail))]
[JsonSerializable(typeof(GraphAttachment))]
[JsonSerializable(typeof(GraphAttachmentItem))]
[JsonSerializable(typeof(GraphAttachmentItemWrapper))]
[JsonSerializable(typeof(GraphInboxRule))]
[JsonSerializable(typeof(GraphInboxRuleActions))]
[JsonSerializable(typeof(GraphInboxRulePredicates))]
[JsonSerializable(typeof(GraphMailboxPermission))]
[JsonSerializable(typeof(GraphMailboxGrantee))]
[JsonSerializable(typeof(GraphEvent))]
[JsonSerializable(typeof(GraphEventAttendee))]
[JsonSerializable(typeof(GraphEventTime))]
[JsonSerializable(typeof(GraphBatchPayload))]
[JsonSerializable(typeof(GraphBatchRequestPayload))]
[JsonSerializable(typeof(GraphSearchPayload))]
[JsonSerializable(typeof(GraphSearchRequest))]
[JsonSerializable(typeof(GraphSearchQuery))]
[JsonSerializable(typeof(GraphDestinationRequest))]
[JsonSerializable(typeof(GraphMarkReadRequest))]
[JsonSerializable(typeof(GraphFolderRenameRequest))]
[JsonSerializable(typeof(GmailMessage))]
[JsonSerializable(typeof(GmailThread))]
[JsonSerializable(typeof(GmailThreadInfo))]
[JsonSerializable(typeof(GmailAttachmentInfo))]
[JsonSerializable(typeof(GmailRawRequest))]
[JsonSerializable(typeof(GmailApiClient.AttachmentResponse))]
[JsonSerializable(typeof(GmailApiClient.GmailListResponse))]
[JsonSerializable(typeof(GmailApiClient.GmailThreadListResponse))]
[JsonSerializable(typeof(Attachment))]
[JsonSerializable(typeof(SendGridMessage))]
[JsonSerializable(typeof(SendGridPersonalization))]
[JsonSerializable(typeof(SendGridEmailAddress))]
[JsonSerializable(typeof(SendGridContent))]
[JsonSerializable(typeof(SendGridAttachment))]
[JsonSerializable(typeof(PendingMessageRepositoryOptions))]
[JsonSerializable(typeof(Dictionary<string, string[]>))]
[JsonSerializable(typeof(Dictionary<string, IList<string>>))]
public partial class MailozaurrJsonContext : JsonSerializerContext;
