using System.Text.Json.Serialization;

namespace Mailozaurr;

/// <summary>Source-generated Microsoft Graph JSON metadata.</summary>
[JsonSourceGenerationOptions(PropertyNameCaseInsensitive = true, DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull)]
[JsonSerializable(typeof(GraphAuthorization))]
[JsonSerializable(typeof(GraphApiError))]
[JsonSerializable(typeof(GraphApiErrorDetail))]
[JsonSerializable(typeof(GraphApiInnerError))]
[JsonSerializable(typeof(GraphApiDiagnostic))]
[JsonSerializable(typeof(GraphApiErrorHeaders))]
[JsonSerializable(typeof(GraphApiErrorResponse))]
[JsonSerializable(typeof(GraphApiServerInfo))]
[JsonSerializable(typeof(GraphSmtpResult))]
[JsonSerializable(typeof(GraphUploadSessionResult))]
[JsonSerializable(typeof(GraphMessage))]
[JsonSerializable(typeof(GraphMessageContainer))]
[JsonSerializable(typeof(GraphContent))]
[JsonSerializable(typeof(GraphEmailAddress))]
[JsonSerializable(typeof(GraphEmail))]
[JsonSerializable(typeof(GraphAttachment))]
[JsonSerializable(typeof(GraphAttachmentItem))]
[JsonSerializable(typeof(GraphAttachmentItemWrapper))]
[JsonSerializable(typeof(GraphInboxRule))]
[JsonSerializable(typeof(GraphInboxRuleActions))]
[JsonSerializable(typeof(GraphInboxRulePredicates))]
[JsonSerializable(typeof(GraphMailboxPermission))]
[JsonSerializable(typeof(GraphMailboxGrantee))]
[JsonSerializable(typeof(GraphEvent))]
[JsonSerializable(typeof(GraphEventAttendee))]
[JsonSerializable(typeof(GraphEventTime))]
[JsonSerializable(typeof(GraphBatchPayload))]
[JsonSerializable(typeof(GraphBatchRequestPayload))]
[JsonSerializable(typeof(GraphSearchPayload))]
[JsonSerializable(typeof(GraphSearchRequest))]
[JsonSerializable(typeof(GraphSearchQuery))]
[JsonSerializable(typeof(GraphDestinationRequest))]
[JsonSerializable(typeof(GraphMarkReadRequest))]
[JsonSerializable(typeof(GraphSetFlagRequest))]
[JsonSerializable(typeof(GraphSetFlagRequestFlag))]
[JsonSerializable(typeof(GraphFolderRenameRequest))]
[JsonSerializable(typeof(GraphApiClient.GraphCreateSubscriptionRequest))]
[JsonSerializable(typeof(GraphApiClient.GraphRenewSubscriptionRequest))]
[JsonSerializable(typeof(GraphApiClient.GraphSubscription))]
[JsonSerializable(typeof(GraphApiClient.GraphSubscriptionListResponse))]
internal partial class GraphJsonContext : JsonSerializerContext;
