<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Company>Evotec</Company>
        <Authors>Przemyslaw Klys</Authors>
        <AssemblyName>Mailozaurr.Application</AssemblyName>
        <TargetFrameworks>netstandard2.0;net8.0</TargetFrameworks>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(TargetFramework)' == 'net8.0' ">
        <IsAotCompatible>true</IsAotCompatible>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Mailozaurr\Mailozaurr.csproj" />
    </ItemGroup>

    <ItemGroup Condition=" '$(TargetFramework)' == 'netstandard2.0' ">
        <PackageReference Include="System.Text.Json" Version="10.0.9" />
    </ItemGroup>

    <ItemGroup>
        <None Include="..\..\Mailozaurr.png" Pack="true" PackagePath="\" />
        <None Include="..\..\README.MD" Pack="true" PackagePath="\" />
    </ItemGroup>
</Project>
